flags:
  HDBC:
    mintime15: false
  cgi:
    old-mtl: true
extra-include-dirs:
- /home/kazu/tools/include
extra-package-dbs: []
ghc-options:
  ! '*': -fPIC -fobject-code
extra-lib-dirs:
- /home/kazu/tools/lib
packages:
- '.'
- /home/kazu/tools/detector-characterization/HasKAL
extra-deps:
- Chart-cairo-1.4
- Chart-gtk-1.4
- HDBC-2.4.0.1
- HDBC-mysql-0.6.6.2
- HDBC-session-0.1.1.0
- HROOT-0.8
- HROOT-core-0.8
- HROOT-graf-0.8
- HROOT-hist-0.8
- HROOT-io-0.8
- HROOT-math-0.8
- bindings-gsl-0.2.1
- carray-0.1.6.5
- cgi-3001.2.2.3
- fficxx-runtime-0.2.1
- fft-0.1.8.1
- hmatrix-gsl-stats-0.4.1.1
- hmatrix-special-0.3.0.1
- ix-shapable-0.1.0
- matrices-0.4.3
- names-th-0.2.0.2
- persistable-record-0.4.0.3
- relational-query-0.8.3.1
- relational-query-HDBC-0.6.0.2
- relational-schemas-0.1.3.1
- sql-words-0.1.4.1
- th-data-compat-0.0.2.2
- th-reify-compat-0.0.1.1
resolver: lts-2.14
