flags:
  semigroupoids:
    tagged: true
extra-include-dirs:
- /home/kazu/tools/include
- /home/kazu/kagali/include
ghc-options:
  ! '*': -fPIC -fobject-code
extra-lib-dirs:
- /home/kazu/tools/lib
- /home/kazu/tools/lib/gsl
- /home/kazu/kagali/lib
packages:
- '.'
extra-deps:
- Chart-gtk-1.6
- HDBC-mysql-0.6.6.4
- HROOT-0.8
- HROOT-core-0.8
- HROOT-graf-0.8
- HROOT-hist-0.8
- HROOT-io-0.8
- HROOT-math-0.8
- QuickCheck-2.11.3
- aeson-1.2.4.0
- base-orphans-0.6
- bindings-DSL-1.0.24
- bindings-gsl-0.2.1
- carray-0.1.6.8
- chunked-data-0.3.1
- conduit-combinators-1.0.8.3
- conduit-extra-1.2.3.2
- cpphs-1.20.8
- fficxx-0.2.1
- fficxx-runtime-0.2.1
- fsnotify-0.2.1.1
- hmatrix-special-0.4.0.1
- mmorph-1.1.0
- mono-traversable-1.0.8.1
- persistable-record-0.6.0.0
- product-isomorphic-0.0.3.1
- relational-query-0.11.0.0
- relational-query-HDBC-0.6.6.1
- relational-schemas-0.1.6.1
- semigroupoids-5.0.1
- tagged-0.8.5
- transformers-compat-0.5.1.4
- text-1.2.2.2
- th-abstraction-0.2.6.0
- typed-process-0.2.1.0
- unix-compat-0.5.0.1
- unliftio-core-0.1.1.0
resolver: lts-6.35
