flags:
  carray:
    bytestringinbase: false
  HDBC:
    mintime15: false
  cgi:
    old-mtl: true
extra-include-dirs:
- /home/kazu/tools/include
ghc-options:
  "*": -fPIC -fobject-code
extra-lib-dirs:
- /home/kazu/tools/lib
packages:
- '.'
- location:
    git: https://github.com/bos/hdbc-mysql.git
    commit: d43ea057019ff683f278f36af410f4d3cbc731bc
extra-deps:
- Chart-1.5.3
- Chart-cairo-1.5.1
- Chart-gtk-1.5.1
- HDBC-2.4.0.1
- HDBC-session-0.1.0.0
- HROOT-0.8
- HROOT-core-0.8
- HROOT-graf-0.8
- HROOT-hist-0.8
- HROOT-io-0.8
- HROOT-math-0.8
- bindings-gsl-0.2.1
- carray-0.1.5.2
- cgi-3001.2.2.2
- fficxx-runtime-0.2.1
- fft-0.1.8.1
- hmatrix-special-0.3.0.1
- hmatrix-gsl-stats-0.4.1.1
- ix-shapable-0.1.0
- matrices-0.4.2
- names-th-0.1.0.1
- persistable-record-0.1.0.1
- relational-query-0.6.0.0
- relational-query-HDBC-0.1.0.1
- relational-schemas-0.1.2.0
- sql-words-0.1.3.1
- HasKAL-0.1.0.0
resolver: lts-2.14
